### PR TITLE
Fix tools to be consistent with scalastyle

### PR DESCRIPTION
**Pull request by jtescher**
Most style violations were:
+ multiline if block without braces
+ public methods having explicit type
+ license header

### CODE REVIEW

**Comment by dszeto** [comment]
Thanks!

**Comment by jtescher** [comment]
Any idea why this isn't reflected in the contributor graph? https://github.com/PredictionIO/PredictionIO/graphs/contributors

**Comment by dszeto** [comment]
Odd indeed. According to https://help.github.com/articles/i-don-t-see-myself-in-the-repository-contributors-graph/, your name should have shown up.

**Comment by dszeto** [comment]
Hey, I just realized your commits are associated with your gmail.com e-mail address. You will need to associate that e-mail address with your GitHub account for you to show up on the contributor graph. Once you've done it, GitHub should update automatically.

**Comment by jtescher** [comment]
Oh yeah! Thanks fixed it.

**Pull request merged**
