### PR TITLE
Adds enhancements for bash files in bin and make-distributions.sh

### PR DESCRIPTION
**Pull request by zafarella**
This will:
* add enhancements for bash scripts in bin
* add colors to important messages in bash scripts

### CODE REVIEW

**Comment by dszeto** [comment]
Thanks for the contribution! Regarding the colors that you have added, could you strip away the leading space, and return to the default color after the color is used? This could be merged once fixed.

**Comment by zafarella** [comment]
Should be good - pls review. Thanks.

**Comment by dszeto** [comment]
Looking good. Manually merging.

**Comment by dszeto** [comment]
By the way, could you associate your e-mail address to your GitHub account? By doing so your name could be cited properly on GitHub's contributor's graph. Thanks!

**Pull request merged**
