### PR TITLE
Delete tmp files in case corrupted

### PR DESCRIPTION
**Pull request by ngheungyu**
I encountered an error before where interrupting the tar download would cause subsequent install attempts to fail. Deleting the tmp file would make sure it gets download again.

### CODE REVIEW

**Comment by dszeto** [comment]
It would be nice to retain the cache functionality, because it is useful during development not needing to re-download large files every time.

**Comment by ngheungyu** [comment]
ok, i will add 4 questions for that then


Best Regards,
Nicholas

**Comment by ngheungyu** [comment]
added, please review.

**Comment by dszeto** [comment]
Looking good and tested on our side as well. Thanks!

**Pull request merged**
