### PR TITLE
Delete application data in non-interactive mode

### LINKED ISSUE #149: Delete application data in non-interactive mode
Please provide a way to delete application data without user interaction, so this can be automated (i.e in bash scripts). E.g.:

    pio app data-delete -y MyApp

### PR DESCRIPTION
**Pull request by schon**
Add --yes, -y option when deleting app and channel.
It is useful to execute a batch script

Closes #149

### CODE REVIEW

**Comment by pferrel** [comment]
Looks good. Can we have a --force CLI instead of --yes, More self-explanatory

**Comment by schon** [comment]
@pferrel Thanks for your comment. I totally agree with you to use "--force". What do you think about short option "-y". Do you think we don't need a short option or change "-f" in accordance with "--force"?

**Comment by pferrel** [comment]
yes to -f.

**Comment by schon** [comment]
@pferrel Modified it. Could you please check this PR. Thanks.

**Pull request merged**
