### PR TITLE
Improve Java installation and locating in install.sh

### PR DESCRIPTION
**Pull request by pawel-n**
I have encountered some issues with the install.sh script on Gentoo linux. Installing Java thrown errors (apt-get...) and JAVA_HOME detection failed (because in Gentoo javac is a symlink to "/usr/libexec/eselect-java/run-java-tool.bash").

The script now:
* lets you decide if you want to install Java or not, and asks you for your distro if you do (currently only Debian/Ubuntu is supported),
* checks if JAVA_HOME is correct and in case of failure lets the user input the path manually,
* uses "read -e -p ..." which enables auto-completion of paths.

I have tested it only on Gentoo.

### CODE REVIEW

**Comment by dszeto** [comment]
Thanks a lot for the PR @pawel-n ! Before I could merge your PR, would you mind signing our CLA at http://prediction.io/cla first?

**Comment by pawel-n** [comment]
I have signed it.

**Comment by dszeto** [comment]
Thanks!

**Comment by ramaboo** [comment]
Thanks @pawel-n Code looks great! I made a few wording changes and rewrote our other loop to use your confirm method which is really handy to have. I also moved a few things around to make sure our Docker install path remains interactive free.

I love how are script is getting better every day. If you have any more suggestions please let us know.  We will be rolling out these changes on install.prediction.io shorty!

**Pull request merged**
