### PR TITLE
Change repo order, and follow redirect with curl

### PR DESCRIPTION
**Pull request by tuxdna**
Fix fo following issue:

https://github.com/PredictionIO/PredictionIO/issues/146

### CODE REVIEW

**Comment by pferrel** [comment]
A lot of people getting this error, @tuxdna ok to pull?

BTW good to see you here.

**Comment by pferrel** [comment]
@dszeto any opinion on this? other than adding verbose to curl and wget he changed the order of repos to search and told curl and wget to follow redirects. 

haven't used this version though

**Comment by tuxdna** [comment]
The real issue here is that the repo "typesafe.artifactoryonline.com" doesn't contain a valid "sbt-launch.jar".

And, the second repo "repo.typesafe.com", does have a valid "sbt-launch.jar", but then it requires wget/curl to follow redirects.

This exactly what this patch fixes.

**Comment by pferrel** [comment]
lot of people seeing this so merging and will test

**Pull request merged**
